/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dice.view;

/**
 *
 * @author marco
 */
public class DiceView extends javax.swing.JFrame
{

  /**
   * @return the lbNumber
   */
  public javax.swing.JLabel getLbNumber1()
  {
    return lbNumber1;
  }

  /**
   * @return the btnStart
   */
  public javax.swing.JButton getBtnStart()
  {
    return btnStart;
  }

  /**
   * @return the btnStop
   */
  public javax.swing.JButton getBtnStop()
  {
    return btnStop;
  }

  /**
   * Creates new form diceView
   */
  public DiceView()
  {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {

    jPanel1 = new javax.swing.JPanel();
    btnStart = new javax.swing.JButton();
    btnStop = new javax.swing.JButton();
    jPanel2 = new javax.swing.JPanel();
    lbNumber1 = new javax.swing.JLabel();
    lbNumber2 = new javax.swing.JLabel();
    lbNumber3 = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    btnStart.setText("Start");
    jPanel1.add(btnStart);

    btnStop.setText("Stop");
    jPanel1.add(btnStop);

    getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

    lbNumber1.setFont(new java.awt.Font("Tahoma", 0, 100)); // NOI18N
    lbNumber1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    lbNumber1.setText("1");
    jPanel2.add(lbNumber1);

    lbNumber2.setFont(new java.awt.Font("Tahoma", 0, 100)); // NOI18N
    lbNumber2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    lbNumber2.setText("1");
    jPanel2.add(lbNumber2);

    lbNumber3.setFont(new java.awt.Font("Tahoma", 0, 100)); // NOI18N
    lbNumber3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    lbNumber3.setText("1");
    jPanel2.add(lbNumber3);

    getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

    setSize(new java.awt.Dimension(416, 339));
    setLocationRelativeTo(null);
  }// </editor-fold>//GEN-END:initComponents

  /**
   * @param args the command line arguments
   */
  public static void main(String args[])
  {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try
    {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
      {
        if ("Nimbus".equals(info.getName()))
        {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    }
    catch (ClassNotFoundException ex)
    {
      java.util.logging.Logger.getLogger(DiceView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (InstantiationException ex)
    {
      java.util.logging.Logger.getLogger(DiceView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (IllegalAccessException ex)
    {
      java.util.logging.Logger.getLogger(DiceView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (javax.swing.UnsupportedLookAndFeelException ex)
    {
      java.util.logging.Logger.getLogger(DiceView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable()
    {
      public void run()
      {
        new DiceView().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnStart;
  private javax.swing.JButton btnStop;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JLabel lbNumber1;
  private javax.swing.JLabel lbNumber2;
  private javax.swing.JLabel lbNumber3;
  // End of variables declaration//GEN-END:variables

  /**
   * @return the lbNumber2
   */
  public javax.swing.JLabel getLbNumber2()
  {
    return lbNumber2;
  }

  /**
   * @return the lbNumber3
   */
  public javax.swing.JLabel getLbNumber3()
  {
    return lbNumber3;
  }
}
